spec:
  name: barangay247
  services:
  - name: web
    github:
      repo: npsangco/barangay247
      branch: main
      deploy_on_push: true
    build_command: composer install --no-dev --optimize-autoloader && npm install && npm run build
    run_command: php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080
    http_port: 8080
    environment_slug: php
    envs:
    - key: APP_NAME
      value: "Barangay 24/7"
    - key: APP_ENV
      value: production
    - key: APP_DEBUG
      value: "false"
    - key: APP_KEY
      value: base64:PsX56oIKKEz3DxQyBLFyhWTS3V4VVHudSooXEa9GroY=
    - key: LOG_CHANNEL
      value: errorlog
    - key: SESSION_DRIVER
      value: cookie
    - key: CACHE_DRIVER
      value: file
    - key: QUEUE_CONNECTION
      value: sync
    - key: DB_CONNECTION
      value: mysql
    - key: DB_HOST
      value: ${db.HOSTNAME}
    - key: DB_PORT
      value: ${db.PORT}
    - key: DB_DATABASE
      value: ${db.DATABASE}
    - key: DB_USERNAME
      value: ${db.USERNAME}
    - key: DB_PASSWORD
      value: ${db.PASSWORD}
  databases:
  - engine: MYSQL
    name: db
    num_nodes: 1
    size: db-s-1vcpu-1gb
    version: "8"
